/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class loadlib_LoadLib */

#ifndef _Included_loadlib_LoadLib
#define _Included_loadlib_LoadLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loadlib_LoadLib
 * Method:    SegmentALine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_loadlib_LoadLib_SegmentALine
  (JNIEnv *, jclass, jstring);


JNIEXPORT jboolean JNICALL Java_loadlib_LoadLib_Init 
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
